### ISSUE TITLE
Error when generating sample from copula

### ISSUE THREAD

**Issue by amrods** [AnderGray/BivariateCopulas.jl#10]
There is something going on with the interpolation.
```julia
using BivariateCopulas
using Random

Random.seed!(123)

τ = 10
K = Clayton(τ)

samplecop = rand(K, 10)
# ERROR: LoadError: knot-vectors must be unique and sorted in increasing order
```

**Comment by amrods** [comment]
If you want, I can implement another sampler for the Clayton copula:
```julia
function _clasample(n, τ)
    r = rand(n, 2)
    for i in 1:size(rng, 1)
        v = r[i, 2]
        u = r[i, 1]
        r[i, 2] = (1 - u^(-τ) + (u^(1 + τ)*v)^(-(τ/(1 + τ))))^(-1/τ)
    end
    return r
end
```
Then in `sample` in line 91 of `copulas.jl` we call that sampler, similar to what you already do for the Gaussian copula in line 97.

**Comment by AnderGray** [comment]
Hi, thanks for raising this issue and giving the solution!

That would be wonderful. Thanks :D
